#!/bin/bash
#PBS -l nodes=1,vmem=16gb,walltime=0:30:00
#PBS -N app-eccentricity-classification

mkdir -p classification

time singularity exec -e docker://brainlife/mcr:neurodebian1604-r2017a ./compiled/eccentricityClassification

if [ -f output.mat ]; then
	echo "complete"
	mkdir -p classification
	mv output.mat ./classification/classification.mat
	mv tracts ./classification/
	mv output_fibercounts.txt ./classification/
	exit 0
else
	echo "failed"
	exit 1
fi
