#!/bin/bash
#PBS -l nodes=1:ppn=1,vmem=20gb,walltime=1:30:00
#PBS -N app-segment-wbtractogram

set -ex

[ ! -d track ] && mkdir track
# [ ! -d wmc ] && mkdir wmc
[ ! -d raw ] && mkdir raw

# create assignments for each tract and parcel in parcellations
if [ ! -f tmp.csv ]; then
	time singularity exec -e docker://brainlife/mrtrix3:3.0.0 ./segment.sh
fi

# final check
if [ ! -f track/track.tck ]; then
	echo "segmentation failed. see logs and derivatives"
	exit 1
else
	echo "segmentation complete"
	mv *.txt *.csv ./raw/
	exit 0
fi
